spring.config.import=optional:file:.env[.properties]

spring.application.name=web-application

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.jpa.properties.hibernate.dialect=${DB_DIALECT}

spring.mvc.hiddenmethod.filter.enabled=true

api.auth.secret.key=${SECRET_KEY}