spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL_PROD}
spring.datasource.username=${DB_USER_PROD}
spring.datasource.password=${DB_PASSWORD_PROD}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false